version: "3.8"

services:
  php:
    container_name: slim_php8.3
    build:
      context: ./docker/php/
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/slim-rest-api

  nginx:
    container_name: slim_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/slim-rest-api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php